### ISSUE TITLE
没有release文件

### ISSUE THREAD

**Issue by kotlinnut** [MrXiaoM/MiraiDailySign#1]

**Comment by MrXiaoM** [comment]
插件还没写好，未经测试，这个月因为一些不可抗力的因素我被迫搁置我的所有项目，没那么快发版。

**Comment by kotlinnut** [comment]
谢谢，mirai的签到插件太稀缺了，我找遍论坛和仓库也找不到，明明是很日常向的功能。大佬加油

**Comment by RankFrank4010** [comment]
对啊

**Comment by MrXiaoM** [comment]
插件已经差不多完成了，还没完全测试，可能会有一些小bug，还有一些新功能没加，可以先自己编译用着
